version: 2

project_name: kubectl-consolidation

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: kubectl-consolidation
    binary: kubectl-consolidation
    main: ./cmd/kubectl-consolidation
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: ssoriche
    name: kubectl-consolidation
  draft: false
  prerelease: auto
  mode: append
  footer: |
    ## Installation

    ### Via krew (recommended)
    ```bash
    kubectl krew install consolidation
    ```

    ### Manual installation
    Download the appropriate binary for your platform, extract it, and place it in your PATH.

    ```bash
    # Example for macOS (Apple Silicon)
    tar -xzf kubectl-consolidation_darwin_arm64.tar.gz
    chmod +x kubectl-consolidation
    sudo mv kubectl-consolidation /usr/local/bin/
    ```
